# Generated by Django 4.2.4 on 2023-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
